apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: hrvb1vbo5-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/hrvb1vbo5-java-quarkus-gitops